###
POST http://localhost:5007/v1/Categories HTTP/1.1
Content-Type: application/json

{
  "Title": "Supermercado",
  "Description": "Supermercado Compras",
  "UserId": "3f4525ff-0a84-4f34-9ed2-e4b866a1a17b"
}
###
GET http://localhost:5007/v1/Categories HTTP/1.1

###
